apiVersion: v1
kind: Service
metadata:
  name: augury-service
  namespace: staging
spec:
  type: NodePort
  selector:
    app: augury
  ports:  
    - name: main
      port: 8080
      targetPort: 8080
      nodePort: 30808
