properties([pipelineTriggers([githubPush()])])

node {
    stage("Nu Fetch") {
        git url: "https://github.com/ozlevka/augury.git"
    }
    
    
    
    stage("Hello world") {
        echo "Hello world"
    }
}