apiVersion: v1
kind: Pod
metadata:
  name: test-slave
spec:
  containers:
    - name: ubuntu-test
      image: ubuntu:20.04
      command:
      - /bin/bash
      - -c
      - "while sleep 1000; do :; done"