apiVersion: v1
kind: Pod
metadata:
  name: test-slave
spec:
  containers:
    - name: docker
      image: docker:20.10.7-dind
      securityContext:
        privileged: true
      env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-token
            key: token
      volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
  volumes:
  - name: dind-storage
    emptyDir: {}