apiVersion: v1
kind: Pod
metadata:
  name: test-slave
spec:
  containers:
    - name: docker
      image: docker:20.10.7-dind
      env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-token
            key: token
      - name: DOCKER_HOST
        value: "tcp://localhost:2375"
      command:
      - /bin/sh
      - -c
      - "while sleep 1000; do :; done"