apiVersion: v1
kind: Pod
metadata:
  name: test-slave
  annotations:
    container.apparmor.security.beta.kubernetes.io/docker: localhost/k8s-apparmor-example-allow-write
spec:
  containers:
    - name: docker
      image: docker:20.10.7-dind
      env:
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-token
            key: token